# Hiperparametry estymatorow

## D2LS

In [34]:
import pandas as pd
df = pd.read_csv("../tables/D2LS_test_results.csv")

In [35]:
best = df[df["blad"] == df["blad"].min()]

In [36]:
best

   Estymator  przyspieszenie  predkosc  wspolczynnik odleglosci    blad
86   D2LS_v2             1.1       0.9                      0.7  574.54

## DLS

In [22]:
import pandas as pd
df_dls = pd.read_csv("../tables/DLS_test_results.csv")

In [23]:
best_dls = df_dls[df_dls["blad"] == df_dls["blad"].min()]

In [24]:
best_dls

   Estymator przyspieszenie  predkosc  wspolczynnik odleglosci    blad
29       DLS              -      0.95                      0.7  579.63

## LS

In [31]:
import pandas as pd
df_ls = pd.read_csv("../tables/LS_test_results.csv")

In [32]:
best_ls = df_ls[df_ls["blad"] == df_ls["blad"].min()]

In [33]:
best_ls

   Estymator przyspieszenie predkosc  wspolczynnik odleglosci    blad
14        LS              -        -                     0.65  630.74