# Hiperparametry estymatorow

## D2LS

In [1]:
import pandas as pd
df = pd.read_csv("../tables/D2LS_test_results.csv")

In [49]:
best = df[df["blad"] == df["blad"].min()]

In [50]:
best

    Estymator  przyspieszenie  predkosc  wspolczynnik odleglosci    blad
450   D2LS_v2            1.05       0.9                     0.71  573.46

## DLS

In [37]:
import pandas as pd
df_dls = pd.read_csv("../tables/DLS_test_results.csv")

In [38]:
best_dls = df_dls[df_dls["blad"] == df_dls["blad"].min()]

In [39]:
best_dls

    Estymator przyspieszenie  predkosc  wspolczynnik odleglosci    blad
155       DLS              -       0.9                     0.71  576.72

## LS

In [40]:
import pandas as pd
df_ls = pd.read_csv("../tables/LS_test_results.csv")

In [41]:
best_ls = df_ls[df_ls["blad"] == df_ls["blad"].min()]

In [42]:
best_ls

   Estymator przyspieszenie predkosc  wspolczynnik odleglosci    blad
14        LS              -        -                     0.65  630.74

## DAMPING

In [ ]:
import pandas as pd
df_d2lsd = pd.read_csv("../tables/D2LSD_test_results.csv")

In [ ]:
best_damp = df_d2lsd[df_d2lsd["blad"] == df_d2lsd["blad"].min()]

In [ ]:
best_damp